springdoc:
  swagger-ui:
    path: '/api'

server:
  port: '8008'

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/slack_int'
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        show_sql: true
        format_sql: true